Enhanced ReplayDataParser with ModeratorEvent Support
FAForever/faf-java-commons pull request #123
Opened 2024-03-20 20:21 UTC by magge-faf

Thanks, @Garanas for the detailed task issue and the examples. Helped me tremendously.

My steps:

1. Created a FAF Develop replay (TestModeratorEvents.fafreplay) with numerous actions (chatting, marker, ping commands, ctrlk+k unit)
2. New class `ModeratorEvent` 
3. New private field `ModeratorEvents` to store the `ModeratorEvent` objects
4. Check for the `ModeratorEvent` in `CMDST_LUA_SIM_CALLBACK`
5. Created a method `parseModeratorEvent`
6. Added unit test to verify that `parseModeratorEvent` correctly parses the replay. (Also, I just console printed out the results I got from parsing and checked it manually first just to be sure)

Output in console:

![image](https://github.com/FAForever/faf-java-commons/assets/101107758/74f424eb-871e-4acb-b01e-b41795573976)

Example was :

`{ From: 1, Message: 'killed 50 units' }`

We have access to the `ModeratorEvents` which are stored in the replay file, and we can build on top of that now.

I have already added the `activeCommandSource` for the future features that will depend on that.

If something needs to be changed, please don't hesitate to comment.

2024-03-20 20:27 UTC, Garanas commented on faf-commons-data/src/main/java/com/faforever/commons/replay/ReplayDataParser.java
> +    Float fromFloat = (Float) lua.get("From");
These should be integers, as they represent the focus army.

2024-03-20 20:28 UTC, Garanas commented on faf-commons-data/src/main/java/com/faforever/commons/replay/ReplayDataParser.java
> +    }
This is not how it works, but it's also not blocking the pull request. We can look into this the next iteration.

2024-03-20 20:29 UTC, Garanas approved these changes
To me this implementation looks like a solid start and can be merged on its own. Perhaps @Sheikah45 and/or @Brutus5000 has additional insights and/or comments

2024-03-21 23:16 UTC, Sheikah45 requested changes

2024-03-21 23:16 UTC, Sheikah45 commented on faf-commons-data/src/main/java/com/faforever/commons/replay/ModeratorEvent.java
> +}
This class can just be a record since all fields are final

2024-03-22 20:53 UTC, Sheikah45 approved these changes

2024-03-22 20:53 UTC, merged