Closes #14 Moderation report api
FAForever/faf-java-commons pull request #15
Opened 2018-08-04 11:32 UTC by bukajsytlos

Closes #14 Moderation report api

2018-08-04 17:14 UTC, axel1200 commented
Well it misses all the security stuff no?

2018-08-04 17:16 UTC, axel1200 commented
Can you also change Ban Info to have a relationship to report as requested in the document and implemted in the db?

2018-08-13 16:23 UTC, micheljung approved these changes

2018-08-13 20:36 UTC, 1-alex98 requested changes

2018-08-13 20:36 UTC, axel1200 commented on faf-commons-api/src/main/java/com/faforever/commons/api/dto/ModerationReport.java
> +  private ModerationReportStatus reportStatus = ModerationReportStatus.AWAITING;
Do you really wanna set default I doubt that, if you wanna make a patch then you want it to be null needing it to set to null on very patch is painfull. I would rather not have a default

2018-08-13 20:36 UTC, axel1200 commented on faf-commons-api/src/main/java/com/faforever/commons/api/dto/ModerationReport.java
> +  private Collection<BanInfo> bans;
BanInfo links ModerationReport and ModerationReport links BanInfo. Just saying, but you will notice soon enough you will need to make one relationShip manged and the other one not.

2018-08-13 20:36 UTC, axel1200 commented on faf-commons-api/src/main/java/com/faforever/commons/api/dto/Player.java
> +    private Set<ModerationReport> reporterOnModerationReports;
Same as above. But you will notice as soons as you modify modor. You can change it then I guess. Btw you can also use none develop commits to use modor with, you dont need to wait for this getting merged into develop ;)

2018-08-15 15:15 UTC, 1-alex98 approved these changes

2018-08-29 19:13 UTC, Brutus5000 approved these changes

2018-08-29 19:14 UTC, merged