Server message to apply player's vetoes
FAForever/faf-java-commons pull request #201
Opened 2024-12-25 12:46 UTC by K-ETFreeman

New server message to apply player's vetoes

2024-12-28 11:37 UTC, K-ETFreeman commented
added teamSize to matchmaker queue dto

2024-12-30 20:40 UTC, Brutus5000 approved these changes

2024-12-30 20:41 UTC, Brutus5000 commented
Your base branch seens not be up-to-date. 15 commits for lines of code indicates that.
Cannot merge `This branch cannot be rebased due to conflicts`

2025-02-06 10:05 UTC, K-ETFreeman commented
doing some changes due to new antirep strategy anyway, so its good that this wanst merged yet

2025-03-23 16:54 UTC, K-ETFreeman commented
also added matchmakerQueueMapPoolId to VetoData, for better structure and more flexibility in the future

2025-10-07 18:26 UTC, Brutus5000 requested changes

2025-10-07 18:26 UTC, Brutus5000 commented on api/build.gradle.kts
> +  // signAllPublications() // Commented out for JitPack builds
revert

2025-10-07 18:26 UTC, Brutus5000 commented on data/build.gradle.kts
> +  // signAllPublications() // Commented out for JitPack builds
revert

2025-10-07 18:26 UTC, Brutus5000 commented on lobby/build.gradle.kts
> +  // signAllPublications() // Commented out for JitPack builds
revert

2025-10-08 12:32 UTC, Brutus5000 approved these changes

2025-10-08 12:33 UTC, merged