Adding various POJOS
FAForever/faf-java-commons pull request #37
Opened 2020-10-10 22:15 UTC by SKeeneCode

Adding POJOS for Leaderboard, MapPool, MatchmakerQueue and MatchmakerQueueMapPool

2020-10-11 12:45 UTC, Brutus5000 requested changes
We need `@EqualsAndHashCode(callSuper = true)` annotated on all classes

2020-10-11 12:45 UTC, Brutus5000 commented on faf-commons-api/src/main/java/com/faforever/commons/api/dto/MatchmakerQueue.java
> +public class MatchmakerQueue extends AbstractEntity {
Maye add `matchmakerQueueMapPool` relationship

2020-10-11 16:05 UTC, bukajsytlos commented
didn't we move this to api repo?

2020-10-11 16:13 UTC, Brutus5000 commented
I tried but migrated everything to Lombok builders, but then encountered that MapStruct doesn't support builders in our scenario (confirmed by the maintainer).

2020-10-13 09:20 UTC, Brutus5000 approved these changes

2020-10-13 09:20 UTC, merged