WIP: Add CoopScenario entity
FAForever/faf-java-commons pull request #99
Opened 2022-12-14 00:25 UTC by Marc-Spector

2022-12-14 05:56 UTC, Brutus5000 requested changes

2022-12-14 05:56 UTC, Brutus5000 commented on faf-commons-api/src/main/java/com/faforever/commons/api/dto/CoopType.java
> +  // Order is crucial
I don't think the order here is crucial, as we don't need to map it to an int anywhere

2022-12-14 05:56 UTC, Brutus5000 commented on faf-commons-api/src/main/java/com/faforever/commons/api/dto/CoopFaction.java
> +  // Order is crucial
I don't think the order here is crucial, as we don't need to map it to an int anywhere

2022-12-14 14:18 UTC, Brutus5000 approved these changes

2022-12-16 12:04 UTC, Brutus5000 commented
@Marc-Spector Is this still WIP?

2022-12-16 14:36 UTC, Marc-Spector commented
No. The PR is ready to merge

2022-12-18 14:40 UTC, Sheikah45 approved these changes

2022-12-18 14:40 UTC, merged